Add a `TLSConfig` option
jeroenrinzema/psql-wire pull request #67
Opened 2024-06-18 12:47 UTC by k-anshul

This PR adds a `TLSConfig` options apart from existing `Certificates`. 
Clients can set `GetCertificate` inside `tls.Config` which enables zero downtime certificate rotation

2024-08-12 11:39 UTC, jeroenrinzema requested changes

2024-08-12 11:39 UTC, jeroenrinzema commented on handshake.go
> +		}
I like the idea of simply passing a `tls.Config`. I am ok to introduce a breaking change and simply pass the `tls.Config` type directly.

2024-11-11 21:41 UTC, jeroenrinzema approved these changes
Thanks @k-anshul! I have implemented the requested changes as discussed

2024-11-11 21:44 UTC, merged

2024-11-19 12:27 UTC, k-anshul commented
> Thanks @k-anshul! I have implemented the requested changes as discussed

Thanks @jeroenrinzema 
Apologies for not being able to address your comments. I got caught up in some other tasks.